package com.wzcsoft.dzpjdy.dao;

import com.wzcsoft.dzpjdy.domain.Printlog;
import com.wzcsoft.dzpjdy.domain.PrintlogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrintlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table printlog
     *
     * @mbg.generated
     */
    long countByExample(PrintlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table printlog
     *
     * @mbg.generated
     */
    int deleteByExample(PrintlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table printlog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table printlog
     *
     * @mbg.generated
     */
    int insert(Printlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table printlog
     *
     * @mbg.generated
     */
    int insertSelective(Printlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table printlog
     *
     * @mbg.generated
     */
    List<Printlog> selectByExample(PrintlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table printlog
     *
     * @mbg.generated
     */
    Printlog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table printlog
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Printlog record, @Param("example") PrintlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table printlog
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Printlog record, @Param("example") PrintlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table printlog
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Printlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table printlog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Printlog record);
}