package com.wzcsoft.dzpjdy.domain;

public class Curentbillno {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curentbillno.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column curentbillno.curpbillno
     *
     * @mbg.generated
     */
    private String curpbillno;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curentbillno
     *
     * @mbg.generated
     */
    public Curentbillno(Integer id, String curpbillno) {
        this.id = id;
        this.curpbillno = curpbillno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table curentbillno
     *
     * @mbg.generated
     */
    public Curentbillno() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curentbillno.id
     *
     * @return the value of curentbillno.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curentbillno.id
     *
     * @param id the value for curentbillno.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column curentbillno.curpbillno
     *
     * @return the value of curentbillno.curpbillno
     *
     * @mbg.generated
     */
    public String getCurpbillno() {
        return curpbillno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column curentbillno.curpbillno
     *
     * @param curpbillno the value for curentbillno.curpbillno
     *
     * @mbg.generated
     */
    public void setCurpbillno(String curpbillno) {
        this.curpbillno = curpbillno == null ? null : curpbillno.trim();
    }
}