package com.wzcsoft.dzpjdy.domain;

public class Printlog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column printlog.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column printlog.cardno
     *
     * @mbg.generated
     */
    private String cardno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column printlog.patientname
     *
     * @mbg.generated
     */
    private String patientname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column printlog.socialno
     *
     * @mbg.generated
     */
    private String socialno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column printlog.billno
     *
     * @mbg.generated
     */
    private String billno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column printlog.billamount
     *
     * @mbg.generated
     */
    private Double billamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column printlog.printdate
     *
     * @mbg.generated
     */
    private String printdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column printlog.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table printlog
     *
     * @mbg.generated
     */
    public Printlog(Integer id, String cardno, String patientname, String socialno, String billno, Double billamount, String printdate, String remark) {
        this.id = id;
        this.cardno = cardno;
        this.patientname = patientname;
        this.socialno = socialno;
        this.billno = billno;
        this.billamount = billamount;
        this.printdate = printdate;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table printlog
     *
     * @mbg.generated
     */
    public Printlog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column printlog.id
     *
     * @return the value of printlog.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column printlog.id
     *
     * @param id the value for printlog.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column printlog.cardno
     *
     * @return the value of printlog.cardno
     *
     * @mbg.generated
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column printlog.cardno
     *
     * @param cardno the value for printlog.cardno
     *
     * @mbg.generated
     */
    public void setCardno(String cardno) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column printlog.patientname
     *
     * @return the value of printlog.patientname
     *
     * @mbg.generated
     */
    public String getPatientname() {
        return patientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column printlog.patientname
     *
     * @param patientname the value for printlog.patientname
     *
     * @mbg.generated
     */
    public void setPatientname(String patientname) {
        this.patientname = patientname == null ? null : patientname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column printlog.socialno
     *
     * @return the value of printlog.socialno
     *
     * @mbg.generated
     */
    public String getSocialno() {
        return socialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column printlog.socialno
     *
     * @param socialno the value for printlog.socialno
     *
     * @mbg.generated
     */
    public void setSocialno(String socialno) {
        this.socialno = socialno == null ? null : socialno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column printlog.billno
     *
     * @return the value of printlog.billno
     *
     * @mbg.generated
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column printlog.billno
     *
     * @param billno the value for printlog.billno
     *
     * @mbg.generated
     */
    public void setBillno(String billno) {
        this.billno = billno == null ? null : billno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column printlog.billamount
     *
     * @return the value of printlog.billamount
     *
     * @mbg.generated
     */
    public Double getBillamount() {
        return billamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column printlog.billamount
     *
     * @param billamount the value for printlog.billamount
     *
     * @mbg.generated
     */
    public void setBillamount(Double billamount) {
        this.billamount = billamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column printlog.printdate
     *
     * @return the value of printlog.printdate
     *
     * @mbg.generated
     */
    public String getPrintdate() {
        return printdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column printlog.printdate
     *
     * @param printdate the value for printlog.printdate
     *
     * @mbg.generated
     */
    public void setPrintdate(String printdate) {
        this.printdate = printdate == null ? null : printdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column printlog.remark
     *
     * @return the value of printlog.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column printlog.remark
     *
     * @param remark the value for printlog.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}